export const dummyProducts = [
  {
    category: "Baby",
    name: "Practical Fresh Bacon",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7096368124395520",
    title: "Tuna",
    price: "₹357",
    brief: "Practical",
    description: "The Football Is Good For Training And Recreational Purposes",
    noofreviews: 101,
    stars: 4,
    quantity: "97 ml",
    properties: {
      productMaterial: "Cotton",
      productName: "Non molestiae modi nisi. Cum dolorum omnis sapiente. Iste aut totam voluptatem esse blanditiis omnis dignissimos unde beatae.",
    },
  },
  {
    category: "Automotive",
    name: "Licensed Frozen Fish",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2994456213061632",
    title: "Shoes",
    price: "₹137",
    brief: "Oriental",
    description: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    noofreviews: 3521,
    stars: 2,
    quantity: "68 ml",
    properties: {
      productMaterial: "Frozen",
      productName:
        "Ipsa mollitia numquam enim aliquam explicabo deleniti corporis possimus commodi. Debitis quam vitae numquam repellendus amet dignissimos tenetur. Temporibus explicabo consectetur nemo earum sed eius.",
    },
  },
  {
    category: "Jewelery",
    name: "Elegant Soft Gloves",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8844030293049344",
    title: "Hat",
    price: "₹421",
    brief: "Intelligent",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 3928,
    stars: 2,
    quantity: "63 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Pariatur iste repudiandae cupiditate repudiandae explicabo tempora labore quam. Inventore aspernatur temporibus in cum veritatis at modi. Pariatur quae quod sed aspernatur voluptatibus mollitia modi quas.",
    },
  },
  {
    category: "Industrial",
    name: "Tasty Wooden Sausages",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2656822058024960",
    title: "Salad",
    price: "₹716",
    brief: "Refined",
    description: "The Football Is Good For Training And Recreational Purposes",
    noofreviews: 3629,
    stars: 0,
    quantity: "51 ml",
    properties: {
      productMaterial: "Wooden",
      productName: "Expedita reprehenderit maiores eligendi. Fuga voluptatum accusamus. Nulla nemo consequatur tenetur possimus inventore.",
    },
  },
  {
    category: "Grocery",
    name: "Licensed Frozen Mouse",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4158214488719360",
    title: "Shoes",
    price: "₹407",
    brief: "Sleek",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 3026,
    stars: 0,
    quantity: "123 ml",
    properties: {
      productMaterial: "Rubber",
      productName:
        "Et excepturi deleniti sit alias quo sunt assumenda porro expedita. Consectetur numquam quidem nesciunt. At perspiciatis cum suscipit libero omnis eos.",
    },
  },
  {
    category: "Jewelery",
    name: "Rustic Rubber Pizza",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8660706444443648",
    title: "Keyboard",
    price: "₹194",
    brief: "Small",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 1350,
    stars: 0,
    quantity: "191 ml",
    properties: {
      productMaterial: "Fresh",
      productName:
        "Nobis temporibus recusandae impedit sed nostrum molestiae at. Placeat temporibus omnis sunt minus facilis dolores minima ipsa. Asperiores quo mollitia ex ducimus.",
    },
  },
  {
    category: "Music",
    name: "Recycled Soft Fish",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8357890620391424",
    title: "Cheese",
    price: "₹537",
    brief: "Elegant",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 3068,
    stars: 2,
    quantity: "93 ml",
    properties: {
      productMaterial: "Rubber",
      productName:
        "Veritatis beatae voluptates facilis accusantium mollitia ipsum unde. Optio sequi totam aut facere. Possimus expedita delectus tenetur explicabo cumque consequatur atque non.",
    },
  },
  {
    category: "Automotive",
    name: "Refined Fresh Salad",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8908935520059392",
    title: "Pants",
    price: "₹603",
    brief: "Bespoke",
    description: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    noofreviews: 3213,
    stars: 4,
    quantity: "117 ml",
    properties: {
      productMaterial: "Steel",
      productName:
        "Incidunt temporibus neque ad. Aspernatur nulla expedita voluptate voluptate placeat voluptatibus assumenda totam. Reiciendis voluptatem inventore est.",
    },
  },
  {
    category: "Garden",
    name: "Elegant Cotton Computer",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4573061586092032",
    title: "Gloves",
    price: "₹759",
    brief: "Sleek",
    description: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    noofreviews: 3541,
    stars: 4,
    quantity: "38 ml",
    properties: {
      productMaterial: "Soft",
      productName:
        "Nostrum et cum corrupti recusandae ea labore. Unde consequuntur vitae delectus consequuntur dolorem accusantium. Delectus at delectus occaecati totam.",
    },
  },
  {
    category: "Jewelery",
    name: "Tasty Steel Chips",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8987774138974208",
    title: "Tuna",
    price: "₹787",
    brief: "Small",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 2578,
    stars: 4,
    quantity: "141 ml",
    properties: {
      productMaterial: "Plastic",
      productName:
        "Odit amet id quas delectus ex unde consequatur. Sint et id odio fuga expedita dolores. Voluptas eum repudiandae tempora doloremque iusto animi omnis repellat quod.",
    },
  },
  {
    category: "Grocery",
    name: "Incredible Soft Table",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=700146882969600",
    title: "Shoes",
    price: "₹317",
    brief: "Handcrafted",
    description: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    noofreviews: 2672,
    stars: 0,
    quantity: "73 ml",
    properties: {
      productMaterial: "Bronze",
      productName: "Voluptatem natus quidem inventore. Libero odit laborum mollitia magnam hic. Blanditiis nostrum voluptas beatae excepturi vitae.",
    },
  },
  {
    category: "Sports",
    name: "Gorgeous Fresh Bacon",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3655696488857600",
    title: "Chips",
    price: "₹740",
    brief: "Handmade",
    description:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    noofreviews: 2280,
    stars: 4,
    quantity: "180 ml",
    properties: {
      productMaterial: "Soft",
      productName:
        "Eaque sapiente quas occaecati. Consequatur laborum architecto quisquam autem ipsam necessitatibus nam sint. Laboriosam soluta harum quibusdam suscipit neque asperiores dolore exercitationem debitis.",
    },
  },
  {
    category: "Sports",
    name: "Small Cotton Table",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4989078734897152",
    title: "Chicken",
    price: "₹981",
    brief: "Electronic",
    description: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    noofreviews: 1269,
    stars: 2,
    quantity: "40 ml",
    properties: {
      productMaterial: "Bronze",
      productName:
        "Atque numquam ipsam officiis. Quibusdam occaecati cumque debitis iure. Eligendi eos enim perferendis officia sequi provident accusantium ex illo.",
    },
  },
  {
    category: "Computers",
    name: "Handcrafted Frozen Chips",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6994857170042880",
    title: "Sausages",
    price: "₹924",
    brief: "Licensed",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 625,
    stars: 0,
    quantity: "83 ml",
    properties: {
      productMaterial: "Wooden",
      productName: "Cupiditate officia asperiores. Delectus expedita accusantium a provident. Animi cupiditate fugit ea odit.",
    },
  },
  {
    category: "Tools",
    name: "Refined Steel Ball",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7702157654491136",
    title: "Table",
    price: "₹404",
    brief: "Generic",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 955,
    stars: 4,
    quantity: "178 ml",
    properties: {
      productMaterial: "Rubber",
      productName:
        "Ab fugit expedita maxime quia dolorem quia dolores. Quae suscipit quod ut voluptate blanditiis a. Ut officia unde saepe odio sapiente repellat earum consectetur.",
    },
  },
  {
    category: "Computers",
    name: "Electronic Plastic Bike",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7737982605852672",
    title: "Pizza",
    price: "₹694",
    brief: "Small",
    description: "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    noofreviews: 3543,
    stars: 4,
    quantity: "159 ml",
    properties: {
      productMaterial: "Metal",
      productName:
        "Fuga sunt repudiandae molestias inventore culpa voluptatem beatae. Ipsam ullam minus nisi nulla eveniet odit similique quo beatae. Ex a explicabo quia eveniet rerum fugit.",
    },
  },
  {
    category: "Toys",
    name: "Handcrafted Concrete Car",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2605448624603136",
    title: "Table",
    price: "₹708",
    brief: "Fantastic",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 2581,
    stars: 0,
    quantity: "87 ml",
    properties: {
      productMaterial: "Cotton",
      productName:
        "Assumenda dolore ipsam aut numquam quae explicabo hic aliquam. Esse rerum voluptates dolor maiores aliquam soluta. Modi dignissimos expedita ipsum architecto saepe officiis excepturi explicabo.",
    },
  },
  {
    category: "Computers",
    name: "Electronic Fresh Chair",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6237611943264256",
    title: "Salad",
    price: "₹455",
    brief: "Incredible",
    description: "The Football Is Good For Training And Recreational Purposes",
    noofreviews: 532,
    stars: 4,
    quantity: "61 ml",
    properties: {
      productMaterial: "Soft",
      productName:
        "Et illo assumenda rem quaerat fugit hic facere nisi facilis. Facilis iure ipsam vero voluptate ea quaerat. Natus nisi est exercitationem incidunt molestias et nobis.",
    },
  },
  {
    category: "Kids",
    name: "Refined Rubber Table",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6137949804560384",
    title: "Fish",
    price: "₹295",
    brief: "Awesome",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 3477,
    stars: 2,
    quantity: "132 ml",
    properties: {
      productMaterial: "Soft",
      productName:
        "Eum tempore aliquam quasi ullam. Assumenda in suscipit architecto officiis asperiores provident illum fugit. Quasi numquam beatae ipsam suscipit quisquam doloribus molestiae.",
    },
  },
  {
    category: "Home",
    name: "Recycled Frozen Computer",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2926026468360192",
    title: "Towels",
    price: "₹306",
    brief: "Tasty",
    description: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    noofreviews: 2442,
    stars: 2,
    quantity: "41 ml",
    properties: {
      productMaterial: "Plastic",
      productName:
        "Porro aspernatur ad quibusdam omnis aspernatur consectetur exercitationem impedit veritatis. Dolore quidem labore atque magnam. Cum id praesentium accusamus.",
    },
  },
  {
    category: "Electronics",
    name: "Licensed Bronze Shirt",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=993703801913344",
    title: "Computer",
    price: "₹538",
    brief: "Elegant",
    description: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    noofreviews: 1863,
    stars: 4,
    quantity: "76 ml",
    properties: {
      productMaterial: "Steel",
      productName:
        "Nostrum corporis tempore ea aperiam ducimus suscipit dolorum soluta. Totam provident doloribus cumque harum quae quod magnam excepturi. Recusandae ratione quia nulla aspernatur id.",
    },
  },
  {
    category: "Beauty",
    name: "Awesome Bronze Cheese",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=517772687704064",
    title: "Fish",
    price: "₹708",
    brief: "Intelligent",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 1515,
    stars: 0,
    quantity: "30 ml",
    properties: {
      productMaterial: "Bronze",
      productName:
        "Dolores quod quibusdam. Eaque ullam fugit nihil id ab perspiciatis facere. Veritatis eum occaecati voluptatum aliquid nihil facere corrupti quod.",
    },
  },
  {
    category: "Outdoors",
    name: "Bespoke Metal Mouse",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3604982676848640",
    title: "Pants",
    price: "₹354",
    brief: "Gorgeous",
    description: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    noofreviews: 2790,
    stars: 4,
    quantity: "76 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Et quasi eius. Distinctio totam unde veritatis blanditiis quisquam laudantium. Repellat quidem adipisci distinctio accusamus laborum minima.",
    },
  },
  {
    category: "Industrial",
    name: "Handcrafted Bronze Hat",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2221042984550400",
    title: "Computer",
    price: "₹466",
    brief: "Fantastic",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 3194,
    stars: 4,
    quantity: "76 ml",
    properties: {
      productMaterial: "Rubber",
      productName:
        "Maiores perferendis alias doloremque tempora et autem veritatis ab deleniti. Reiciendis cupiditate et provident qui similique consequuntur in. Provident libero ea doloremque doloremque laudantium.",
    },
  },
  {
    category: "Movies",
    name: "Handcrafted Bronze Towels",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6931488018792448",
    title: "Shoes",
    price: "₹282",
    brief: "Rustic",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 1194,
    stars: 2,
    quantity: "174 ml",
    properties: {
      productMaterial: "Steel",
      productName:
        "Aut delectus pariatur recusandae ullam. Commodi doloremque explicabo itaque quaerat pariatur. Nostrum deleniti odit fugit velit ad quaerat totam sunt.",
    },
  },
  {
    category: "Music",
    name: "Unbranded Steel Soap",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5420688057827328",
    title: "Salad",
    price: "₹243",
    brief: "Awesome",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 2752,
    stars: 2,
    quantity: "154 ml",
    properties: {
      productMaterial: "Bronze",
      productName:
        "Vero magnam reprehenderit magni. Atque ipsam iusto ullam quasi voluptatibus ex odit consectetur aliquam. Voluptatibus ea repellat nihil iure.",
    },
  },
  {
    category: "Automotive",
    name: "Unbranded Plastic Soap",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1788918437511168",
    title: "Tuna",
    price: "₹953",
    brief: "Oriental",
    description:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    noofreviews: 3839,
    stars: 2,
    quantity: "57 ml",
    properties: {
      productMaterial: "Bronze",
      productName:
        "Voluptate quaerat eius tempore provident. Molestiae deleniti deserunt tenetur ex quam magnam blanditiis recusandae architecto. Itaque inventore eius maxime eveniet.",
    },
  },
  {
    category: "Tools",
    name: "Practical Cotton Gloves",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1806989673889792",
    title: "Hat",
    price: "₹166",
    brief: "Gorgeous",
    description: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    noofreviews: 1962,
    stars: 0,
    quantity: "72 ml",
    properties: {
      productMaterial: "Metal",
      productName:
        "Veritatis aspernatur consequatur numquam. Quibusdam illo illo perspiciatis inventore sequi reprehenderit necessitatibus at odit. Commodi quis sequi optio.",
    },
  },
  {
    category: "Books",
    name: "Intelligent Soft Pants",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5659614970380288",
    title: "Computer",
    price: "₹453",
    brief: "Rustic",
    description: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    noofreviews: 1078,
    stars: 4,
    quantity: "43 ml",
    properties: {
      productMaterial: "Granite",
      productName:
        "Earum repellat quisquam consequatur dolores at. Magni asperiores labore asperiores repellat totam veritatis. Vero ratione occaecati ea architecto nisi.",
    },
  },
  {
    category: "Home",
    name: "Unbranded Concrete Ball",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5069044281507840",
    title: "Car",
    price: "₹316",
    brief: "Ergonomic",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 844,
    stars: 2,
    quantity: "102 ml",
    properties: {
      productMaterial: "Plastic",
      productName:
        "Delectus ex expedita voluptate. Accusamus veniam assumenda sunt laboriosam reprehenderit. Quibusdam enim consequuntur quos neque perferendis suscipit cupiditate voluptate nesciunt.",
    },
  },
  {
    category: "Shoes",
    name: "Elegant Metal Chicken",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3318222732394496",
    title: "Pizza",
    price: "₹622",
    brief: "Elegant",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 66,
    stars: 2,
    quantity: "109 ml",
    properties: {
      productMaterial: "Plastic",
      productName:
        "Ex fugit nulla deleniti dolorem ipsam accusantium recusandae voluptatum. Reiciendis sit mollitia in saepe quasi. Quod ipsam modi qui ipsam excepturi.",
    },
  },
  {
    category: "Clothing",
    name: "Recycled Rubber Towels",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5030699094507520",
    title: "Car",
    price: "₹235",
    brief: "Oriental",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 428,
    stars: 4,
    quantity: "176 ml",
    properties: {
      productMaterial: "Steel",
      productName: "Atque tenetur adipisci. Rem quia libero. Dolore sapiente unde dolor est.",
    },
  },
  {
    category: "Baby",
    name: "Luxurious Granite Salad",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6669025696284672",
    title: "Cheese",
    price: "₹716",
    brief: "Awesome",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 943,
    stars: 2,
    quantity: "44 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Nisi eveniet est. Nesciunt hic sunt tempore commodi fuga eveniet laudantium esse atque. Quis praesentium odit culpa a aliquam molestiae voluptatum.",
    },
  },
  {
    category: "Industrial",
    name: "Bespoke Cotton Salad",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8767018291429376",
    title: "Pizza",
    price: "₹660",
    brief: "Handcrafted",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 906,
    stars: 0,
    quantity: "121 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Ullam consequatur explicabo. Ullam possimus maxime aperiam quidem consectetur. Autem provident vel deserunt totam nisi excepturi.",
    },
  },
  {
    category: "Books",
    name: "Refined Bronze Sausages",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8402771816480768",
    title: "Fish",
    price: "₹204",
    brief: "Elegant",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 2019,
    stars: 4,
    quantity: "145 ml",
    properties: {
      productMaterial: "Bronze",
      productName:
        "Natus veniam quis reprehenderit optio iure aliquam omnis a. Nobis modi voluptates nihil. Impedit eum neque ducimus minima dolore culpa.",
    },
  },
  {
    category: "Automotive",
    name: "Luxurious Concrete Tuna",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6135413198553088",
    title: "Gloves",
    price: "₹249",
    brief: "Unbranded",
    description: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    noofreviews: 1526,
    stars: 4,
    quantity: "76 ml",
    properties: {
      productMaterial: "Granite",
      productName: "Itaque modi laudantium. Beatae laborum ab iure. Minima quasi voluptas aut enim natus atque.",
    },
  },
  {
    category: "Beauty",
    name: "Sleek Cotton Bacon",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8064322632679424",
    title: "Salad",
    price: "₹412",
    brief: "Rustic",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 3699,
    stars: 0,
    quantity: "83 ml",
    properties: {
      productMaterial: "Steel",
      productName:
        "Fugit aut velit deserunt. Provident recusandae ex doloribus perferendis voluptatibus. Nisi totam nisi eligendi incidunt pariatur consectetur veniam.",
    },
  },
  {
    category: "Beauty",
    name: "Electronic Bronze Shoes",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8552247822647296",
    title: "Shirt",
    price: "₹836",
    brief: "Recycled",
    description: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    noofreviews: 819,
    stars: 2,
    quantity: "70 ml",
    properties: {
      productMaterial: "Soft",
      productName:
        "Odit vero mollitia delectus nulla asperiores modi minus provident. Neque nobis consectetur impedit molestias commodi in sunt. In expedita quis.",
    },
  },
  {
    category: "Tools",
    name: "Gorgeous Concrete Towels",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6287687583531008",
    title: "Shirt",
    price: "₹424",
    brief: "Gorgeous",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 238,
    stars: 0,
    quantity: "72 ml",
    properties: {
      productMaterial: "Steel",
      productName: "Alias ipsam vero accusamus hic. Ut eveniet reprehenderit harum nemo perferendis totam. Rem aliquid autem.",
    },
  },
  {
    category: "Books",
    name: "Gorgeous Granite Mouse",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4487565763674112",
    title: "Chair",
    price: "₹718",
    brief: "Gorgeous",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 92,
    stars: 0,
    quantity: "80 ml",
    properties: {
      productMaterial: "Plastic",
      productName:
        "Quisquam rem magnam eius est maxime iusto nulla a quis. Eum rem libero ea vitae provident iure atque. Blanditiis natus doloremque odit itaque eveniet numquam officia.",
    },
  },
  {
    category: "Movies",
    name: "Refined Fresh Cheese",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1676164615634944",
    title: "Bike",
    price: "₹284",
    brief: "Luxurious",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 467,
    stars: 0,
    quantity: "187 ml",
    properties: {
      productMaterial: "Metal",
      productName:
        "Dolorem natus nostrum dignissimos perspiciatis ad molestiae. Quis id odit at debitis nulla error sint similique earum. Vero nesciunt voluptatibus.",
    },
  },
  {
    category: "Books",
    name: "Refined Rubber Keyboard",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8623422059839488",
    title: "Salad",
    price: "₹597",
    brief: "Gorgeous",
    description: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    noofreviews: 1382,
    stars: 0,
    quantity: "82 ml",
    properties: {
      productMaterial: "Bronze",
      productName:
        "Necessitatibus aut illo dignissimos tempora et aliquam ducimus vero. Illum tempora laborum ipsam ex natus optio. Consectetur necessitatibus sed error laborum neque debitis in nisi.",
    },
  },
  {
    category: "Books",
    name: "Handcrafted Wooden Chair",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8043481721208832",
    title: "Sausages",
    price: "₹966",
    brief: "Rustic",
    description: "The Football Is Good For Training And Recreational Purposes",
    noofreviews: 1045,
    stars: 0,
    quantity: "34 ml",
    properties: {
      productMaterial: "Fresh",
      productName: "Aut praesentium provident laudantium harum. Iste fuga nostrum. Recusandae sit minus.",
    },
  },
  {
    category: "Beauty",
    name: "Oriental Granite Tuna",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6540224704282624",
    title: "Mouse",
    price: "₹394",
    brief: "Sleek",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 3760,
    stars: 2,
    quantity: "85 ml",
    properties: {
      productMaterial: "Granite",
      productName: "Deserunt voluptatem odio beatae ullam. Quae tempore maxime aperiam. Itaque blanditiis voluptatibus ducimus eos fuga.",
    },
  },
  {
    category: "Jewelery",
    name: "Modern Frozen Chips",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8770103455776768",
    title: "Ball",
    price: "₹392",
    brief: "Modern",
    description: "The Football Is Good For Training And Recreational Purposes",
    noofreviews: 2669,
    stars: 0,
    quantity: "30 ml",
    properties: {
      productMaterial: "Granite",
      productName: "Repellat aliquam vel. Eaque rerum sequi fugiat dolorum. Aspernatur ea adipisci.",
    },
  },
  {
    category: "Games",
    name: "Fantastic Concrete Gloves",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5290397723000832",
    title: "Fish",
    price: "₹600",
    brief: "Gorgeous",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 2858,
    stars: 4,
    quantity: "199 ml",
    properties: {
      productMaterial: "Steel",
      productName:
        "Dolore optio saepe inventore adipisci. Incidunt accusantium vel eveniet aliquam molestiae voluptatibus animi deleniti eligendi. Quis corporis earum iure tempora nihil.",
    },
  },
  {
    category: "Kids",
    name: "Gorgeous Granite Hat",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7669860882448384",
    title: "Chicken",
    price: "₹813",
    brief: "Elegant",
    description: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    noofreviews: 2510,
    stars: 4,
    quantity: "192 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Id sunt dignissimos ut reprehenderit similique perspiciatis laudantium. Harum maxime velit quia. Ea quis inventore alias expedita reiciendis itaque ipsam provident.",
    },
  },
  {
    category: "Music",
    name: "Electronic Plastic Table",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1100178954125312",
    title: "Shirt",
    price: "₹858",
    brief: "Generic",
    description:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    noofreviews: 176,
    stars: 2,
    quantity: "167 ml",
    properties: {
      productMaterial: "Concrete",
      productName: "Alias dolore illo nemo porro praesentium. Adipisci autem error cumque. Ipsam voluptate velit vitae odit.",
    },
  },
  {
    category: "Baby",
    name: "Oriental Plastic Gloves",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1424809225355264",
    title: "Fish",
    price: "₹104",
    brief: "Practical",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 1325,
    stars: 2,
    quantity: "118 ml",
    properties: {
      productMaterial: "Fresh",
      productName:
        "Provident dolore quidem vero atque. Omnis impedit quae beatae sit. Voluptatibus nostrum aspernatur doloribus sequi error assumenda quod quia.",
    },
  },
  {
    category: "Industrial",
    name: "Handmade Fresh Chicken",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3606932791230464",
    title: "Mouse",
    price: "₹844",
    brief: "Luxurious",
    description:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    noofreviews: 1812,
    stars: 0,
    quantity: "149 ml",
    properties: {
      productMaterial: "Concrete",
      productName: "Sequi ut cum eius ipsum delectus sed voluptate harum. Necessitatibus culpa accusamus. Omnis ipsum excepturi ad.",
    },
  },
  {
    category: "Automotive",
    name: "Handcrafted Wooden Towels",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3960329205710848",
    title: "Salad",
    price: "₹176",
    brief: "Sleek",
    description:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    noofreviews: 3859,
    stars: 2,
    quantity: "164 ml",
    properties: {
      productMaterial: "Steel",
      productName:
        "Cumque excepturi totam sapiente vitae nisi odit veritatis. Pariatur soluta voluptas quis officia saepe eligendi. Ab inventore amet libero impedit fuga rerum aut.",
    },
  },
  {
    category: "Tools",
    name: "Modern Concrete Gloves",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8524392759820288",
    title: "Bacon",
    price: "₹844",
    brief: "Handmade",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 1821,
    stars: 2,
    quantity: "185 ml",
    properties: {
      productMaterial: "Steel",
      productName:
        "Deserunt reprehenderit doloremque voluptas delectus. Esse necessitatibus rem iste repudiandae aperiam occaecati. Odio et molestias laudantium tempora necessitatibus vel officiis modi distinctio.",
    },
  },
  {
    category: "Clothing",
    name: "Intelligent Plastic Bacon",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7914118098976768",
    title: "Fish",
    price: "₹680",
    brief: "Intelligent",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 3817,
    stars: 2,
    quantity: "170 ml",
    properties: {
      productMaterial: "Rubber",
      productName:
        "Amet dignissimos ut dolores asperiores voluptatem temporibus veniam labore unde. Est id quo id in. Dolore fugiat ullam quod natus libero.",
    },
  },
  {
    category: "Beauty",
    name: "Rustic Fresh Towels",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1761189918932992",
    title: "Bacon",
    price: "₹689",
    brief: "Luxurious",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 239,
    stars: 4,
    quantity: "33 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Totam voluptatum aliquid a voluptatibus vero. Id sapiente at porro eos natus suscipit minus enim vel. Porro illo facere deserunt ratione rerum.",
    },
  },
  {
    category: "Health",
    name: "Elegant Cotton Chair",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=6675795898531840",
    title: "Table",
    price: "₹886",
    brief: "Handmade",
    description:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    noofreviews: 1340,
    stars: 2,
    quantity: "194 ml",
    properties: {
      productMaterial: "Metal",
      productName:
        "Voluptate excepturi dolorum provident accusamus ex tempora dignissimos. Dolores recusandae possimus aut reiciendis. Ad neque quisquam sed aspernatur.",
    },
  },
  {
    category: "Grocery",
    name: "Small Fresh Tuna",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8789524054278144",
    title: "Ball",
    price: "₹295",
    brief: "Electronic",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 1104,
    stars: 2,
    quantity: "82 ml",
    properties: {
      productMaterial: "Fresh",
      productName: "Nam quod architecto sint est. Odio consequuntur quibusdam. Dolorum maxime voluptatum voluptas iure suscipit esse.",
    },
  },
  {
    category: "Beauty",
    name: "Tasty Steel Pants",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5783769558548480",
    title: "Chair",
    price: "₹584",
    brief: "Handmade",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 2085,
    stars: 2,
    quantity: "72 ml",
    properties: {
      productMaterial: "Rubber",
      productName:
        "Soluta iste illum porro eaque in ratione hic odio. Molestias aperiam excepturi molestiae expedita expedita quasi. Assumenda quod non.",
    },
  },
  {
    category: "Computers",
    name: "Small Frozen Computer",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5363131582775296",
    title: "Keyboard",
    price: "₹400",
    brief: "Intelligent",
    description:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    noofreviews: 3880,
    stars: 0,
    quantity: "55 ml",
    properties: {
      productMaterial: "Plastic",
      productName: "Quasi perspiciatis error officia quisquam autem. Sunt nam debitis tenetur iusto quisquam. Recusandae inventore ex ducimus dicta.",
    },
  },
  {
    category: "Baby",
    name: "Gorgeous Bronze Sausages",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5908924429500416",
    title: "Salad",
    price: "₹367",
    brief: "Oriental",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 3557,
    stars: 0,
    quantity: "141 ml",
    properties: {
      productMaterial: "Steel",
      productName:
        "Eum repellendus unde. Sapiente quibusdam accusamus iure dignissimos doloremque in ullam quia. Minus possimus voluptatum exercitationem corrupti commodi commodi suscipit.",
    },
  },
  {
    category: "Outdoors",
    name: "Modern Steel Computer",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7769238905290752",
    title: "Towels",
    price: "₹876",
    brief: "Generic",
    description: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    noofreviews: 1629,
    stars: 0,
    quantity: "94 ml",
    properties: {
      productMaterial: "Bronze",
      productName: "Commodi at nemo. Velit quos atque nisi. Magnam eius iure.",
    },
  },
  {
    category: "Jewelery",
    name: "Bespoke Plastic Sausages",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8351856751280128",
    title: "Mouse",
    price: "₹972",
    brief: "Incredible",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 204,
    stars: 2,
    quantity: "200 ml",
    properties: {
      productMaterial: "Soft",
      productName: "Ullam modi deleniti a voluptatem quia et totam. Rerum ipsam est tempore officiis. Itaque ipsam dolorem omnis.",
    },
  },
  {
    category: "Baby",
    name: "Luxurious Wooden Pizza",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5553998604009472",
    title: "Shoes",
    price: "₹525",
    brief: "Gorgeous",
    description: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    noofreviews: 1608,
    stars: 0,
    quantity: "172 ml",
    properties: {
      productMaterial: "Bronze",
      productName: "Laudantium odio placeat tenetur voluptatum. Voluptates debitis maiores. Nulla eveniet atque eveniet et.",
    },
  },
  {
    category: "Toys",
    name: "Refined Fresh Shoes",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3345181149495296",
    title: "Fish",
    price: "₹349",
    brief: "Electronic",
    description: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    noofreviews: 2741,
    stars: 0,
    quantity: "161 ml",
    properties: {
      productMaterial: "Soft",
      productName: "Consequuntur cum ipsa labore vero commodi quidem pariatur. Blanditiis magnam voluptate temporibus libero. Unde fugit amet.",
    },
  },
  {
    category: "Books",
    name: "Gorgeous Frozen Pants",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7188480727711744",
    title: "Hat",
    price: "₹472",
    brief: "Practical",
    description: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    noofreviews: 1266,
    stars: 4,
    quantity: "47 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Nisi aut quaerat consequatur asperiores sapiente ratione illo illo ab. Laborum nostrum neque dicta dolores dicta. Itaque exercitationem reiciendis doloremque autem reprehenderit commodi occaecati.",
    },
  },
  {
    category: "Tools",
    name: "Modern Bronze Keyboard",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4969052864774144",
    title: "Computer",
    price: "₹148",
    brief: "Licensed",
    description: "The Football Is Good For Training And Recreational Purposes",
    noofreviews: 2383,
    stars: 0,
    quantity: "86 ml",
    properties: {
      productMaterial: "Granite",
      productName:
        "Sunt fuga molestias tempore velit laborum dolor molestiae. Amet rerum voluptate ipsa. Ad nesciunt deleniti laborum odit qui dolores maxime.",
    },
  },
  {
    category: "Movies",
    name: "Licensed Plastic Fish",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2361512010186752",
    title: "Table",
    price: "₹816",
    brief: "Generic",
    description: "The Football Is Good For Training And Recreational Purposes",
    noofreviews: 2794,
    stars: 4,
    quantity: "39 ml",
    properties: {
      productMaterial: "Fresh",
      productName:
        "Porro dolorum enim porro laudantium. Ipsa architecto dolor id voluptatem similique maxime laborum maiores veritatis. Accusamus quisquam non quasi.",
    },
  },
  {
    category: "Music",
    name: "Handmade Frozen Towels",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8558215927169024",
    title: "Cheese",
    price: "₹859",
    brief: "Rustic",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 2947,
    stars: 4,
    quantity: "88 ml",
    properties: {
      productMaterial: "Concrete",
      productName: "Amet nam quos reprehenderit qui expedita. Mollitia itaque voluptates. Deserunt dolore quia dolorem quasi exercitationem.",
    },
  },
  {
    category: "Home",
    name: "Rustic Soft Chicken",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3541554429952000",
    title: "Shirt",
    price: "₹674",
    brief: "Sleek",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 2403,
    stars: 0,
    quantity: "33 ml",
    properties: {
      productMaterial: "Rubber",
      productName: "Debitis soluta sed quidem sunt a possimus explicabo. Qui assumenda facere. Exercitationem rem dolorem harum enim.",
    },
  },
  {
    category: "Garden",
    name: "Modern Fresh Gloves",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8347811741433856",
    title: "Chips",
    price: "₹432",
    brief: "Generic",
    description: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    noofreviews: 652,
    stars: 2,
    quantity: "73 ml",
    properties: {
      productMaterial: "Rubber",
      productName: "Nostrum magni aliquid minima. Dicta ad voluptatem provident aut ipsa ullam voluptatibus. Nam velit cupiditate.",
    },
  },
  {
    category: "Automotive",
    name: "Handmade Fresh Hat",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2493836683116544",
    title: "Keyboard",
    price: "₹263",
    brief: "Oriental",
    description: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    noofreviews: 3267,
    stars: 2,
    quantity: "162 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Deleniti hic modi magnam soluta fugiat delectus asperiores molestias. Et quam aspernatur culpa. Consequatur quos autem voluptas fugiat quae soluta libero alias repellendus.",
    },
  },
  {
    category: "Tools",
    name: "Small Granite Chicken",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1601090625732608",
    title: "Table",
    price: "₹279",
    brief: "Luxurious",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 1117,
    stars: 2,
    quantity: "47 ml",
    properties: {
      productMaterial: "Rubber",
      productName: "Id amet enim nihil. Vitae deleniti velit earum minima magni. Ex corporis dolores deleniti ut cupiditate nemo iure itaque.",
    },
  },
  {
    category: "Shoes",
    name: "Unbranded Plastic Bacon",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7223532608028672",
    title: "Cheese",
    price: "₹165",
    brief: "Bespoke",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 1303,
    stars: 0,
    quantity: "192 ml",
    properties: {
      productMaterial: "Plastic",
      productName: "Praesentium numquam hic distinctio. Aperiam quidem maxime voluptatem aliquid recusandae hic ab aperiam harum. Iusto error eaque.",
    },
  },
  {
    category: "Home",
    name: "Handmade Fresh Shoes",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3451976232730624",
    title: "Car",
    price: "₹834",
    brief: "Licensed",
    description: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    noofreviews: 2665,
    stars: 4,
    quantity: "147 ml",
    properties: {
      productMaterial: "Metal",
      productName: "Harum in amet natus provident asperiores. Non nobis fugit inventore. Illo itaque ad explicabo cum assumenda perspiciatis.",
    },
  },
  {
    category: "Music",
    name: "Rustic Wooden Car",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7079020801818624",
    title: "Computer",
    price: "₹733",
    brief: "Gorgeous",
    description:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    noofreviews: 1403,
    stars: 4,
    quantity: "69 ml",
    properties: {
      productMaterial: "Plastic",
      productName:
        "Aut accusamus quasi placeat. Tempore voluptatibus nemo temporibus numquam ex. Pariatur ipsam quidem sed natus rerum tempore occaecati.",
    },
  },
  {
    category: "Industrial",
    name: "Electronic Steel Ball",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1196077392855040",
    title: "Sausages",
    price: "₹469",
    brief: "Tasty",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 967,
    stars: 4,
    quantity: "151 ml",
    properties: {
      productMaterial: "Fresh",
      productName:
        "Aliquid ipsa dolorum laudantium explicabo occaecati tenetur. Magni nihil saepe accusamus quam pariatur occaecati dolores a. Molestiae sapiente nam.",
    },
  },
  {
    category: "Books",
    name: "Generic Cotton Tuna",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8408218021658624",
    title: "Tuna",
    price: "₹181",
    brief: "Generic",
    description:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    noofreviews: 1865,
    stars: 2,
    quantity: "114 ml",
    properties: {
      productMaterial: "Metal",
      productName:
        "Soluta occaecati rem consequatur soluta corporis ipsam harum nemo. Incidunt pariatur labore cumque nesciunt accusamus ut. Quia neque numquam deserunt occaecati.",
    },
  },
  {
    category: "Kids",
    name: "Unbranded Soft Chair",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=782683858796544",
    title: "Table",
    price: "₹694",
    brief: "Generic",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 2147,
    stars: 0,
    quantity: "169 ml",
    properties: {
      productMaterial: "Fresh",
      productName: "Asperiores ipsa maiores sint vel doloribus. Beatae modi dolorem saepe. Incidunt voluptas sit a.",
    },
  },
  {
    category: "Beauty",
    name: "Awesome Soft Computer",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4775546342866944",
    title: "Ball",
    price: "₹205",
    brief: "Rustic",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 3595,
    stars: 4,
    quantity: "176 ml",
    properties: {
      productMaterial: "Soft",
      productName:
        "Reprehenderit voluptate debitis a deserunt amet voluptas. Architecto aperiam a odio magnam vitae ea eius rerum voluptates. Repellendus nostrum exercitationem possimus a facere earum totam blanditiis similique.",
    },
  },
  {
    category: "Electronics",
    name: "Licensed Soft Salad",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8371123452379136",
    title: "Pizza",
    price: "₹515",
    brief: "Electronic",
    description: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    noofreviews: 3756,
    stars: 2,
    quantity: "93 ml",
    properties: {
      productMaterial: "Frozen",
      productName:
        "Aliquam odio natus minus laborum impedit quaerat. Vel quis veritatis modi consequuntur. Saepe repellat voluptate nihil debitis aliquid.",
    },
  },
  {
    category: "Automotive",
    name: "Oriental Steel Chips",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8628422936887296",
    title: "Gloves",
    price: "₹438",
    brief: "Electronic",
    description: "The Football Is Good For Training And Recreational Purposes",
    noofreviews: 3754,
    stars: 2,
    quantity: "200 ml",
    properties: {
      productMaterial: "Fresh",
      productName: "Impedit veniam voluptatum. Dolore esse quam ipsa sit quaerat iste rem necessitatibus at. Nobis commodi corrupti.",
    },
  },
  {
    category: "Movies",
    name: "Unbranded Concrete Tuna",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1156260661559296",
    title: "Tuna",
    price: "₹749",
    brief: "Handmade",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 1208,
    stars: 4,
    quantity: "174 ml",
    properties: {
      productMaterial: "Frozen",
      productName: "Nemo nemo veniam architecto illum id dolores quo dolor corrupti. Velit tenetur repellendus architecto. Quis porro occaecati.",
    },
  },
  {
    category: "Computers",
    name: "Refined Wooden Shirt",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3435539132841984",
    title: "Shirt",
    price: "₹647",
    brief: "Oriental",
    description:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    noofreviews: 2520,
    stars: 4,
    quantity: "43 ml",
    properties: {
      productMaterial: "Metal",
      productName: "Deleniti blanditiis laborum possimus. Iusto quae sed alias doloremque quod vero similique. Corporis incidunt voluptatum.",
    },
  },
  {
    category: "Computers",
    name: "Tasty Metal Chicken",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2445628957261824",
    title: "Soap",
    price: "₹692",
    brief: "Fantastic",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 3174,
    stars: 4,
    quantity: "71 ml",
    properties: {
      productMaterial: "Rubber",
      productName:
        "Reprehenderit aliquid odit nisi omnis veritatis. Eveniet harum enim mollitia eveniet ex voluptatem ipsum. Earum sequi quaerat excepturi ratione aspernatur praesentium quidem.",
    },
  },
  {
    category: "Jewelery",
    name: "Electronic Granite Chicken",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4773759636471808",
    title: "Pizza",
    price: "₹751",
    brief: "Elegant",
    description:
      "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    noofreviews: 2185,
    stars: 0,
    quantity: "195 ml",
    properties: {
      productMaterial: "Frozen",
      productName:
        "Quam quidem magni a corporis porro. Consequuntur maiores beatae maxime ratione aut quos ipsum. Odit molestiae quia temporibus nemo maiores ducimus.",
    },
  },
  {
    category: "Toys",
    name: "Refined Bronze Computer",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5092465778360320",
    title: "Bike",
    price: "₹384",
    brief: "Handmade",
    description:
      "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    noofreviews: 1013,
    stars: 4,
    quantity: "100 ml",
    properties: {
      productMaterial: "Wooden",
      productName:
        "Consectetur qui aliquid blanditiis doloribus architecto minus perspiciatis est commodi. Est magnam sapiente dolorum amet sint hic quae blanditiis sunt. Nemo veniam aperiam repellendus animi consequatur nemo labore id.",
    },
  },
  {
    category: "Beauty",
    name: "Awesome Plastic Chips",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4846400789544960",
    title: "Gloves",
    price: "₹335",
    brief: "Recycled",
    description: "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    noofreviews: 3102,
    stars: 4,
    quantity: "116 ml",
    properties: {
      productMaterial: "Metal",
      productName:
        "Necessitatibus harum beatae dolor incidunt nemo ipsum. Laborum occaecati ad. Vel tempore pariatur mollitia corrupti mollitia sed ducimus rem libero.",
    },
  },
  {
    category: "Industrial",
    name: "Small Rubber Sausages",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5150388554563584",
    title: "Sausages",
    price: "₹694",
    brief: "Sleek",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 3623,
    stars: 4,
    quantity: "48 ml",
    properties: {
      productMaterial: "Bronze",
      productName:
        "Voluptate veritatis aut provident unde ullam sint. Dolor nobis recusandae laudantium. Quam quam provident ratione odio cumque quas.",
    },
  },
  {
    category: "Computers",
    name: "Fantastic Wooden Chips",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=4344808757788672",
    title: "Pants",
    price: "₹103",
    brief: "Generic",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 2783,
    stars: 2,
    quantity: "159 ml",
    properties: {
      productMaterial: "Metal",
      productName:
        "Earum ut deleniti voluptatum magnam quisquam aut consequatur provident minus. Debitis ex expedita cum voluptate repudiandae. Sint occaecati a.",
    },
  },
  {
    category: "Jewelery",
    name: "Handcrafted Rubber Pants",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7707786009903104",
    title: "Keyboard",
    price: "₹354",
    brief: "Sleek",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 3886,
    stars: 2,
    quantity: "197 ml",
    properties: {
      productMaterial: "Cotton",
      productName:
        "Harum sit laborum tempora ex voluptas porro. Aperiam odit maxime dolorum. Molestiae omnis voluptatum nesciunt velit debitis eius sit ducimus.",
    },
  },
  {
    category: "Outdoors",
    name: "Sleek Rubber Salad",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7537531899871232",
    title: "Fish",
    price: "₹750",
    brief: "Handcrafted",
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    noofreviews: 3679,
    stars: 4,
    quantity: "160 ml",
    properties: {
      productMaterial: "Frozen",
      productName:
        "Rem quia asperiores quisquam hic asperiores hic minus unde reiciendis. Velit rem repudiandae aliquam rem. Quidem eos impedit totam blanditiis consequatur.",
    },
  },
  {
    category: "Shoes",
    name: "Awesome Bronze Keyboard",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2866334201282560",
    title: "Bacon",
    price: "₹957",
    brief: "Modern",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 562,
    stars: 2,
    quantity: "46 ml",
    properties: {
      productMaterial: "Fresh",
      productName:
        "Eius perspiciatis illum mollitia illum ut. Possimus nisi natus molestiae eligendi. Ipsum consequatur enim maiores tempora magnam in.",
    },
  },
  {
    category: "Grocery",
    name: "Tasty Granite Keyboard",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7693824136577024",
    title: "Salad",
    price: "₹719",
    brief: "Licensed",
    description: "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    noofreviews: 3660,
    stars: 2,
    quantity: "159 ml",
    properties: {
      productMaterial: "Metal",
      productName:
        "Eius voluptas alias saepe sunt numquam nisi modi. Ut dignissimos soluta corporis iure impedit quibusdam voluptate minus sunt. Incidunt similique animi nihil aspernatur.",
    },
  },
  {
    category: "Sports",
    name: "Modern Soft Bike",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=7446811618836480",
    title: "Table",
    price: "₹352",
    brief: "Rustic",
    description: "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    noofreviews: 1441,
    stars: 0,
    quantity: "162 ml",
    properties: {
      productMaterial: "Granite",
      productName:
        "Quam eligendi quidem adipisci incidunt possimus voluptatibus qui reprehenderit optio. Earum placeat molestias quisquam repellat. Commodi molestiae at.",
    },
  },
  {
    category: "Shoes",
    name: "Awesome Wooden Pants",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=1994927896526848",
    title: "Shirt",
    price: "₹227",
    brief: "Licensed",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 3784,
    stars: 2,
    quantity: "193 ml",
    properties: {
      productMaterial: "Frozen",
      productName:
        "Minus sapiente ducimus quibusdam reiciendis reiciendis labore. Ipsum delectus maiores deleniti reprehenderit praesentium nulla maxime. Veniam qui quidem officia.",
    },
  },
  {
    category: "Baby",
    name: "Modern Wooden Chicken",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=8729006041989120",
    title: "Pizza",
    price: "₹976",
    brief: "Tasty",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 3817,
    stars: 4,
    quantity: "97 ml",
    properties: {
      productMaterial: "Plastic",
      productName:
        "Exercitationem ducimus harum vel. Sunt deserunt veritatis. Excepturi esse nobis laudantium itaque consequuntur consequuntur provident optio.",
    },
  },
  {
    category: "Computers",
    name: "Refined Plastic Fish",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2684408171593728",
    title: "Salad",
    price: "₹890",
    brief: "Fantastic",
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    noofreviews: 2526,
    stars: 2,
    quantity: "163 ml",
    properties: {
      productMaterial: "Soft",
      productName:
        "Corrupti culpa qui. Tempore iste explicabo explicabo hic in est voluptatibus. Cum veniam recusandae deleniti nemo architecto corrupti dolore.",
    },
  },
  {
    category: "Baby",
    name: "Bespoke Steel Keyboard",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=3851760554737664",
    title: "Soap",
    price: "₹530",
    brief: "Handmade",
    description: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    noofreviews: 1496,
    stars: 2,
    quantity: "191 ml",
    properties: {
      productMaterial: "Granite",
      productName:
        "Mollitia cum distinctio expedita error laboriosam quam animi quisquam reiciendis. Similique voluptatem ipsam maiores incidunt pariatur distinctio velit. Voluptatum enim laboriosam atque laboriosam est voluptas molestiae.",
    },
  },
  {
    category: "Garden",
    name: "Small Fresh Mouse",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=2040417998602240",
    title: "Chicken",
    price: "₹927",
    brief: "Incredible",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 2383,
    stars: 0,
    quantity: "126 ml",
    properties: {
      productMaterial: "Bronze",
      productName:
        "Minima laboriosam porro similique commodi provident iste nemo. Dolorem perspiciatis distinctio. At aperiam eligendi nulla inventore incidunt facilis.",
    },
  },
  {
    category: "Movies",
    name: "Ergonomic Frozen Table",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=841612997427200",
    title: "Salad",
    price: "₹483",
    brief: "Recycled",
    description: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    noofreviews: 3499,
    stars: 4,
    quantity: "42 ml",
    properties: {
      productMaterial: "Concrete",
      productName:
        "Doloribus officia accusamus error quae expedita recusandae modi mollitia tenetur. Nihil aut laborum neque nemo magnam explicabo. A rem esse minima quidem distinctio recusandae odio ab distinctio.",
    },
  },
  {
    category: "Sports",
    name: "Recycled Steel Chair",
    image: "https://loremflickr.com/400/582/cosmetics,product?lock=5941439798181888",
    title: "Soap",
    price: "₹179",
    brief: "Oriental",
    description: "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    noofreviews: 2426,
    stars: 4,
    quantity: "138 ml",
    properties: {
      productMaterial: "Fresh",
      productName: "Esse fugiat similique. Quasi voluptates a enim incidunt excepturi. Totam quam assumenda.",
    },
  },
];